[GLOBAL]
pants_version = "2.9.0rc1"

backend_packages = [
  "pants.backend.experimental.docker",
  "pants.backend.experimental.docker.lint.hadolint",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]


[anonymous-telemetry]
enabled = true
repo_id = "B573B56B-6289-40C5-ADB7-4C5FA659EAD1"


[python]
# Narrow constraint, so that we build Python PEX'es that will be executable by our selected Docker
# base image, `python:3.8`.
interpreter_constraints = [">=3.8,<3.9"]
